//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModelFirstDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class capsule
    {
        public int id { get; set; }
        public string line_number { get; set; }
        public string inline_number { get; set; }
        public string cup_type { get; set; }
        public string cup_color { get; set; }
        public string station { get; set; }
        public string cup_status_ng_ok { get; set; }
        public string NG_type { get; set; }
        public int cup_channel { get; set; }
        public System.DateTime create_time { get; set; }
        public string vendor { get; set; }
        public Nullable<System.DateTime> current_insert_time { get; set; }
    }
}
